# [target.'cfg(all(target_arch = "arm", target_os = "none"))']
[target.thumbv8m.main-none-eabihf]
runner = [
  "probe-rs",
  "run",
  "--chip",
  "STM32H563ZITx",
  "--log-format",
  "{t:blue} {L} {s} {f:magenta}:{l:magenta}",
]

# https://defmt.ferrous-systems.com/custom-log-output

[build]
# target = "thumbv7em-none-eabi"
# target = "thumbv7em-none-eabihf"
target = "thumbv8m.main-none-eabihf"

# trace, debug, info, warn, error, off
[env]
DEFMT_LOG = "debug"
# DEFMT_LOG = "off"